version: '3'
services:
  wildfly: #name of the service
    build:
      context: ./wildfly #location of the Dockerfile
      dockerfile: Dockerfile
      args:
        - WILDFLY_MODE=domain
    ports: #exposed ports
      - "8080:8080"
      - "9990:9990"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres", "-h", "localhost", "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: